FROM openjdk:11-jre-slim

ENV VERSION 0.31.2

# Source: https://git.mikael.io/mikaelhg/broken-docker-jdk9-cacerts#tldr-workaround
RUN /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts \
 && /var/lib/dpkg/info/ca-certificates-java.postinst configure

ADD http://downloads.metabase.com/v$VERSION/metabase.jar /opt/metabase.jar

CMD ["java", "-jar", "/opt/metabase.jar"]
