CREATE TABLE IF NOT EXISTS GUILDS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVE         BOOLEAN DEFAULT true NOT NULL,
    "NAME"         TEXT                 NOT NULL,
    REGION         TEXT                 NOT NULL,
    CREATED_ON     DATETIME             NOT NULL,
    LAST_ACTIVE_ON DATETIME             NOT NULL
);

CREATE TABLE IF NOT EXISTS SETTINGS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTOSAVE           BOOLEAN       DEFAULT false NOT NULL,
    PREFIX             TEXT          DEFAULT '!'   NOT NULL,
    DEFAULTTEXTCHANNEL BIGINT                      NULL,
    VOLUME             DECIMAL(3, 2) DEFAULT 0.8   NOT NULL,
    GUILD              BIGINT                      NOT NULL,
    CONSTRAINT FK_SETTINGS_GUILD_ID FOREIGN KEY (GUILD) REFERENCES GUILDS (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

ALTER TABLE SETTINGS
    ADD CONSTRAINT SETTINGS_GUILD_UNIQUE UNIQUE (GUILD);

CREATE TABLE IF NOT EXISTS ALIASES
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    "NAME"   TEXT   NOT NULL,
    ALIAS    TEXT   NOT NULL,
    SETTINGS BIGINT NOT NULL,
    CONSTRAINT FK_ALIASES_SETTINGS_ID FOREIGN KEY (SETTINGS) REFERENCES SETTINGS (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS CHANNELS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    "NAME"     TEXT   NOT NULL,
    AUTORECORD INT    NULL,
    AUTOSTOP   INT    NULL,
    SETTINGS   BIGINT NOT NULL,
    CONSTRAINT FK_CHANNELS_SETTINGS_ID FOREIGN KEY (SETTINGS) REFERENCES SETTINGS (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS RECORDINGS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    CHANNEL     BIGINT           NOT NULL,
    "SIZE"      BIGINT DEFAULT 0 NOT NULL,
    CREATED_ON  DATETIME         NOT NULL,
    MODIFIED_ON DATETIME         NULL,
    URL         TEXT             NULL,
    GUILD       BIGINT           NOT NULL,
    CONSTRAINT FK_RECORDINGS_CHANNEL_ID FOREIGN KEY (CHANNEL) REFERENCES CHANNELS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_RECORDINGS_GUILD_ID FOREIGN KEY (GUILD) REFERENCES GUILDS (ID) ON DELETE CASCADE ON UPDATE RESTRICT
)
