ALTER TABLE Guilds ALTER COLUMN active DROP DEFAULT;
ALTER TABLE Guilds ALTER active TYPE bool USING CASE WHEN active=0 THEN FALSE ELSE TRUE END;
ALTER TABLE Guilds ALTER COLUMN active SET DEFAULT TRUE;
